<?php
/**
 * Email View - Base Layout
 *
 * @version 1.0
 *
 */

if (!defined('ABSPATH')) {
	exit;
}
?>
<head>
	<?php echo $head; ?>
</head>
<body style="font-family: 'Work Sans', Avenir, Helvetica, sans-serif;box-sizing: border-box;background-color: #f5f8fa;color: #74787E;height: 100%;hyphens: auto;line-height: 1.4;margin: 0;-moz-hyphens: auto;-webkit-hyphens: auto;-webkit-text-size-adjust: none;width: 100% !important;">
<table class="mail-wrapper"
	   style="background-color: #3f3f3f;text-align: center;margin: 0;padding: 0;width: 100%;font-family: 'Work Sans', Avenir, Helvetica, sans-serif;box-sizing: border-box;">
	<tbody>
		<tr>
				<tr>
					<td style="font-family: 'Work Sans', Avenir, Helvetica, sans-serif;box-sizing: border-box;" align="center">
						<tbody class="mail-content"
							   style="margin: 0;padding: 0;width: 100%;font-family: 'Work Sans', Avenir, Helvetica, sans-serif;box-sizing: border-box;">
							<tr>
								<td style="font-family:'Work Sans',Avenir,Helvetica,sans-serif;box-sizing:border-box;padding:25px 0;text-align:center">
									<?php echo $header; ?>
								</td>
							</tr>
						</tbody>
					</td>
				</tr>
				<tr>
					<td style="font-family:'Work Sans',Avenir,Helvetica,sans-serif;box-sizing:border-box;background-color:#ffffff;border-bottom:1px solid #edeff2;border-top:1px solid #edeff2;margin:0;padding:0;width:100%">
						<table
							style="font-family:'Work Sans',Avenir,Helvetica,sans-serif;box-sizing:border-box;background-color:#ffffff;margin:0 auto;padding:0;width:570px">
							<tbody>
							<tr>
								<td class="mail-body"
									style="font-family:'Work Sans',Avenir,Helvetica,sans-serif;box-sizing:border-box;padding:35px">
									<?php echo $content; ?>
								</td>
							</tr>
							<tr>
								<?php echo $footer ?>
							</tr>
							</tbody>
						</table>
					</td>
				</tr>
				<tr>
					<td style="font-family:'Work Sans',Avenir,Helvetica,sans-serif;box-sizing:border-box">
						<table
							style="font-family:'Work Sans',Avenir,Helvetica,sans-serif;box-sizing:border-box;margin:0 auto;padding:0;text-align:center;width:570px">
							<tbody>
							<tr>
								<td style="font-family:'Work Sans',Avenir,Helvetica,sans-serif;box-sizing:border-box;padding:35px">
									<p style="font-family:'Work Sans',Avenir,Helvetica,sans-serif;box-sizing:border-box;line-height:1.5em;margin-top:0;color:#aeaeae;font-size:12px;text-align:center">
										<?php echo $foot ?>
									</p>
								</td>
							</tr>
							</tbody>
						</table>
					</td>
				</tr>
			</tr>
	</tbody>
</table>
</body>
