<?php
/**
 * Email View - Order Item Details
 *
 * @version 1.0
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

    if ( isset( $options ) && ! empty( $options ) ) {
        echo '<br /><br />';
        foreach ($options as $option) {
            echo '<b>' . esc_html( $option['name'] ) . '</b> ' . esc_html( $option['value'] ) . '<br />';
        }
    }
?>
<?php if ( isset( $dynamic_sku ) && ! empty( $dynamic_sku ) ) : ?>
    <br><b>SKU:</b>&nbsp;<?php echo esc_html( $dynamic_sku ); ?>
<?php endif;?>
<?php

if ( isset( $xpv_generated ) && $xpv_generated == true ) {
	$product = wc_get_product( $product_id );
	$quantities = $product->get_meta( 'xpv_grouped_products_quantities' );
	$grouped_products_ids = $product->get_meta('xpv_grouped_products_ids');

	echo '<br />';

	foreach ($grouped_products_ids as $grouped_product_id) {
		$grouped_product = wc_get_product( $grouped_product_id );
		$grouped_product_quantity = $quantities[$grouped_product->get_sku()] * $quantity;

		echo esc_html( $grouped_product->get_name() ). '&nbsp;';
		echo ' <strong class="product-quantity">' . sprintf( '&times;&nbsp;%s', esc_html( $grouped_product_quantity ) ) . '</strong>' . '<br />';
	}
}
?>
